### ISSUE TITLE
will the plugin take over all the notification generated by kibana's ```Notifier```

### ISSUE THREAD

**Issue by xycloud** [sw-jung/kibana_notification_center#2]
will the plugin take over all the notification generated by kibana's ```Notifier```

**Comment by sw-jung** [comment]
Currently, all notifications that occurred by kibana's `Notifier` are displayed in the notification_center panel.
 😸

**Comment by sw-jung** [comment]
Added a NOTE to the README to help understand.

See 9c16578715258f3d73528e995b1d64f85408b859

Thank you.
